# Docker Compose para Produção
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-prod
    restart: always
    env_file:
      - .env.prod
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_prod:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend-prod
    env_file:
      - .env.prod
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    command: mvn spring-boot:run -Dspring-boot.run.profiles=prod
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        # Em produção, usar o domínio real ou IP do servidor
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL:-http://backend:8080/api/v1}
    container_name: frontend-prod
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  mysql_data_prod:

networks:
  app-network:
    driver: bridge
